In [1]:
import torch
y = torch.tensor([1,2,3,4,5])

print(y)#singlelist

tensor([1, 2, 3, 4, 5])


In [2]:
d = torch.tensor([
    [13,33],
    [42,99]
])
print(d)

tensor([[13, 33],
        [42, 99]])


In [3]:
z=torch.zeros(4,5)
o = torch.ones(3,3)
print(z)
print("====================")
print(o)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [4]:
r = torch.rand(5,4)

print(r)

print(r.shape)

tensor([[0.2425, 0.2388, 0.9588, 0.8343],
        [0.6631, 0.5305, 0.4895, 0.4404],
        [0.1441, 0.8879, 0.2268, 0.4024],
        [0.0882, 0.6480, 0.8940, 0.4156],
        [0.5982, 0.3832, 0.5984, 0.7080]])
torch.Size([5, 4])


In [5]:
# access

k = torch.tensor([
    [4,5,6],
    [9,12,5],
    [4,10,19]
])

print(k[0,2])
print(k[2,1])

tensor(6)
tensor(10)


In [6]:

a = torch.tensor([1,4,1])
b = torch.tensor([9,3,12])


print(a+b)
print(a*b)

tensor([10,  7, 13])
tensor([ 9, 12, 12])


In [16]:
x = torch.tensor([1,2,3,4,5,6,7,8,9,10])
y = torch.tensor([4,9,15,17,20,22,24,29,33,44])

w = torch.tensor(0.0,requires_grad=True)
b = torch.tensor(0.0,requires_grad=True)

y_pred =w*x +b

loss = (((y_pred) - y **2).mean())
print("predicted value : ",y_pred)
print("actual value : ",y)

print("loss : ",loss)


loss.backward()

print("gradient of w:", w.grad)
print("gradient of b:", b.grad)

print("loss : ",loss)


predicted value :  tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], grad_fn=<AddBackward0>)
actual value :  tensor([ 4,  9, 15, 17, 20, 22, 24, 29, 33, 44])
loss :  tensor(-593.7000, grad_fn=<MeanBackward0>)
gradient of w: tensor(5.5000)
gradient of b: tensor(1.0000)
loss :  tensor(-593.7000, grad_fn=<MeanBackward0>)
