In [1]:
import torch
y = torch.tensor([1,2,3,4,5])

print(y)#singlelist

tensor([1, 2, 3, 4, 5])


In [2]:
d = torch.tensor([
    [13,33],
    [42,99]
])
print(d)

tensor([[13, 33],
        [42, 99]])


In [3]:
z=torch.zeros(4,5)
o = torch.ones(3,3)
print(z)
print("====================")
print(o)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [4]:
r = torch.rand(5,4)

print(r)

print(r.shape)

tensor([[0.2425, 0.2388, 0.9588, 0.8343],
        [0.6631, 0.5305, 0.4895, 0.4404],
        [0.1441, 0.8879, 0.2268, 0.4024],
        [0.0882, 0.6480, 0.8940, 0.4156],
        [0.5982, 0.3832, 0.5984, 0.7080]])
torch.Size([5, 4])


In [5]:
# access

k = torch.tensor([
    [4,5,6],
    [9,12,5],
    [4,10,19]
])

print(k[0,2])
print(k[2,1])

tensor(6)
tensor(10)


In [6]:

a = torch.tensor([1,4,1])
b = torch.tensor([9,3,12])


print(a+b)
print(a*b)

tensor([10,  7, 13])
tensor([ 9, 12, 12])


In [17]:
x = torch.tensor([1,2,3,4,5,6,7,8,9,10])
y = torch.tensor([4,9,15,17,20,22,24,29,33,44])

w = torch.tensor(0.0,requires_grad=True)
b = torch.tensor(0.0,requires_grad=True)

y_pred =w*x +b

loss = ((y_pred - y) ** 2).mean()
print("predicted value : ",y_pred)
print("actual value : ",y)

print("loss : ",loss)


loss.backward()

print("gradient of w:", w.grad)
print("gradient of b:", b.grad)

print("loss : ",loss)


predicted value :  tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], grad_fn=<AddBackward0>)
actual value :  tensor([ 4,  9, 15, 17, 20, 22, 24, 29, 33, 44])
loss :  tensor(593.7000, grad_fn=<MeanBackward0>)
gradient of w: tensor(-300.8000)
gradient of b: tensor(-43.4000)
loss :  tensor(593.7000, grad_fn=<MeanBackward0>)


In [20]:
x = torch.tensor([1,2,3,4,5,6,7,8,9,10])
y = torch.tensor([4,9,15,17,20,22,24,29,33,44])

w = torch.tensor(0.0,requires_grad=True)
b = torch.tensor(0.0,requires_grad=True)

y_pred =w*x +b

loss = ((y_pred - y) ** 2).mean()
print("predicted value : ",y_pred)
print("actual value : ",y)

print("loss : ",loss)


loss.backward()

print("gradient of w:", w.grad)
print("gradient of b:", b.grad)

print("loss : ",loss)

learning_rate = 0.01

with torch.no_grad():
    w -= learning_rate * w.grad
    b -= learning_rate * b.grad

print("new w:", w)
print("new b:", b)

print("====================================")
x = torch.tensor([1,2,3,4,5,6,7,8,9,10])
y = torch.tensor([4,9,15,17,20,22,24,29,33,44])

w = torch.tensor(w,requires_grad=True)
b = torch.tensor(b,requires_grad=True)

y_pred =w*x +b

loss = ((y_pred - y) ** 2).mean()
print("predicted value : ",y_pred)
print("actual value : ",y)

print("loss : ",loss)

predicted value :  tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], grad_fn=<AddBackward0>)
actual value :  tensor([ 4,  9, 15, 17, 20, 22, 24, 29, 33, 44])
loss :  tensor(593.7000, grad_fn=<MeanBackward0>)
gradient of w: tensor(-300.8000)
gradient of b: tensor(-43.4000)
loss :  tensor(593.7000, grad_fn=<MeanBackward0>)
new w: tensor(3.0080, requires_grad=True)
new b: tensor(0.4340, requires_grad=True)
predicted value :  tensor([ 3.4420,  6.4500,  9.4580, 12.4660, 15.4740, 18.4820, 21.4900, 24.4980,
        27.5060, 30.5140], grad_fn=<AddBackward0>)
actual value :  tensor([ 4,  9, 15, 17, 20, 22, 24, 29, 33, 44])
loss :  tensor(32.9570, grad_fn=<MeanBackward0>)


C:\Users\Admin\AppData\Local\Temp\ipykernel_13908\929044925.py:36: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  w = torch.tensor(w,requires_grad=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_13908\929044925.py:37: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  b = torch.tensor(b,requires_grad=True)


In [2]:
import torch

x = torch.tensor([1.,2.,3.,4.,5.,6.,7.,8.,9.,10.])
y = torch.tensor([4.,9.,15.,17.,20.,22.,24.,29.,33.,44.])

w = torch.tensor(0.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

learning_rate = 0.01

for epoch in range(1000):

    # prediction
    y_pred = w * x + b

    # loss
    loss = ((y_pred - y) ** 2).mean()

    # gradients
    loss.backward()

    # update
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad

    # reset gradients
    w.grad.zero_()
    b.grad.zero_()

    if epoch % 100 == 0:
            print(
        "Epoch:", epoch,
        "| Loss:", loss.item(),
        "| Weight (w):", w.item(),
        "| Bias (b):", b.item()
    )

Epoch: 0 | Loss: 593.7000122070312 | Weight (w): 3.008000135421753 | Bias (b): 0.4339999556541443
Epoch: 100 | Loss: 5.967805862426758 | Weight (w): 3.8059024810791016 | Bias (b): 0.7057502865791321
Epoch: 200 | Loss: 5.957155704498291 | Weight (w): 3.791383981704712 | Bias (b): 0.8068258762359619
Epoch: 300 | Loss: 5.952567100524902 | Weight (w): 3.7818527221679688 | Bias (b): 0.873181939125061
Epoch: 400 | Loss: 5.950587272644043 | Weight (w): 3.775595188140869 | Bias (b): 0.916744589805603
Epoch: 500 | Loss: 5.94973611831665 | Weight (w): 3.771487236022949 | Bias (b): 0.9453431367874146
Epoch: 600 | Loss: 5.949367046356201 | Weight (w): 3.7687904834747314 | Bias (b): 0.9641178250312805
Epoch: 700 | Loss: 5.949210166931152 | Weight (w): 3.7670199871063232 | Bias (b): 0.976443350315094
Epoch: 800 | Loss: 5.949143409729004 | Weight (w): 3.765857696533203 | Bias (b): 0.9845351576805115
Epoch: 900 | Loss: 5.9491167068481445 | Weight (w): 3.765094757080078 | Bias (b): 0.9898471832275391
